Bugfix for undefined method `deep_symbolize_keys'
I'm using stripe_event on a new Rails 5 project, while listening to the
webhook "account.application.deauthorized" in my tests & in my event application
logs I was noticing the error :

```
NoMethodError:
       undefined method `deep_symbolize_keys' for
       #<ActionController::Parameters:0x007fe84b498780>
```

This was being thrown on lib/stripe_event.rb around line 20.

I wrote a fix which converts the ActionController::Parameters into a
hash, however I was unable to get the stripe_events specs running my end
(When I ran `bundle exec rake spec` I kept running into "cannot load
such file" errors). I've annotated in the specs where I believe they need to be
corrected.

I'm happy to update the specs if someone can't point me in the right
direction on how to set them up.